import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-heading",
  subsets: ["latin"],
});

const SITE_URL = "https://ah-ha-wedding.vercel.app";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Ah-Ha! | Wedding Planning Made Simple",
  description:
    "The wedding planner that picks up where vendor booking ends. Timelines, seating charts, checklists, and every detail you didn't know you needed.",
  openGraph: {
    title: "Ah-Ha! — Everything they forgot to mention",
    description:
      "From the first vendor call to the last dance. Vendor playbooks, minute-by-minute day-of scripts, per-person handouts, and every detail no one else tells you. Built by someone who survived their own wedding.",
    url: SITE_URL,
    siteName: "Ah-Ha!",
    locale: "en_US",
    type: "website",
    // images auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Ah-Ha! — Everything they forgot to mention",
    description:
      "The wedding planner that picks up where vendor booking ends. Built by someone who survived their own wedding.",
    // images auto-inherited from opengraph-image.tsx
  },
  // favicon + apple-icon auto-registered (apple-icon.tsx). Explicit icons config removed.
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${playfair.variable} h-full`}>
      <body className="min-h-full flex flex-col antialiased">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
